# Generated by Django 5.2.5 on 2025-10-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibility',
            name='ans1',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Nill', max_length=3),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='ans10',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Nill', max_length=3),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='ans11',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Nill', max_length=3),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='ans12',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Nill', max_length=3),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='ans13',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Nill', max_length=3),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='ans14',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Nill', max_length=3),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='ans15',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Nill', max_length=3),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='ans16',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Nill', max_length=3),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='ans17',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Nill', max_length=3),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='ans18',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Nill', max_length=3),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='ans19',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Nill', max_length=3),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='ans2',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Nill', max_length=3),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='ans20',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Nill', max_length=3),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='ans3',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Nill', max_length=3),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='ans4',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Nill', max_length=3),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='ans5',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Nill', max_length=3),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='ans6',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Nill', max_length=3),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='ans7',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Nill', max_length=3),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='ans8',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Nill', max_length=3),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='ans9',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Nill', max_length=3),
        ),
    ]
