# Generated by Django 5.2.5 on 2025-08-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_donors_donateddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
