# Generated by Django 5.2.5 on 2025-10-07 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
