# Generated by Django 5.2.5 on 2025-08-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_donors_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='mob',
            field=models.IntegerField(max_length=15),
        ),
    ]
