# Generated by Django 5.2.5 on 2025-09-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_donors_mob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='mob',
            field=models.IntegerField(),
        ),
    ]
